---
# ZMK firmware build matrix
# Split keyboard: left + right nice!nano
# Shield: none (naudojam custom PCB / custom wiring)
# Studio support įjungtas

include:
  - board: nice_nano_v1
    shield: none
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: left
  - board: nice_nano_v1
    shield: none
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: right
